# Generated by Django 4.2.11 on 2024-03-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=122)),
                ('name', models.CharField(max_length=122)),
                ('desciption', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
